# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 장혜미
title: 개발 이력서
email: hyemi.jang02@gmail.com
website: www.github.com/jang-hyemi/jang-hyemi

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  jang-hyemi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: www.linkedin.com/in/혜미-장-12b108404
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: https://www.youtube.com/channel/UCNd2YIk840IpmQa0AS9xwyQ
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pinn.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: 2026 졸업작품 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: English script practice robot project
        link: github.com/Triplelingo/ScriptRobotProject
        # link_text: Project Website
        additional_links:
          - title:  jang-hyemi/modern-resume-theme
            icon: fab fa-github
            url: github.com/Triplelingo/ScriptRobotProject
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          key : Emotional NLP, Raspberry Pi Robotics, Human-Robot Interaction(HRI), Speech Assessment
        description: | # this will include new lines to allow paragraphs
          사용자가 웹에 영어 대본을 업로드하면 시스템이 자동으로 등장인물과 감정을 분류하고,
          머리 형태의 라즈베리파이 로봇이 LCD 입 모양과 고갯짓으로 상대방 역할을 수행하여
          사용자가 실제 대화하듯 영어 대본을 연습할 수 있는 시스템.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 엠브레이스
        link: https://embracelabs.com/
        # link_text: boringcompany.com
        sub_title: 실시간 스트리밍 서비스 광고 운영 및 모니터링
        caption: 2024년 7월 - 재직중
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 동양미래대학교
        caption: 2023 - 2026
        sub_title: 컴퓨터소프트웨어공학과
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
